"""1.3

Revision ID: 122afb659322
Revises: 96cbb67285a6
Create Date: 2025-05-31 02:26:21.155142

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

from app.utils import OptimizedPydanticMutableJSON
# revision identifiers, used by Alembic.
revision: str = '122afb659322'
down_revision: Union[str, None] = '96cbb67285a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tv_category', sa.Enum('HOT_CN_DRAMA', 'HOT_US_EU_DRAMA', 'HOT_JP_DRAMA', 'HOT_KR_DRAMA', 'HOT_ANIME', 'OTHER', name='tvcategory'), nullable=True),
    sa.Column('episodes_info',sa.JSON, nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('quark_disk_info', sa.JSON, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
