"""1.5

Revision ID: 3137e7c72ffb
Revises: 7399881aca9b
Create Date: 2025-06-15 15:00:56.116152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3137e7c72ffb'
down_revision: Union[str, None] = '7399881aca9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('cloud_disk_info', mysql.JSON(), nullable=True))
    op.drop_column('resource', 'quark_disk_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('quark_disk_info', mysql.JSON(), nullable=True))
    op.drop_column('resource', 'cloud_disk_info')
    # ### end Alembic commands ###
