"""1.3

Revision ID: 3e6f36f76e4a
Revises: f5f5c9e1b6f5
Create Date: 2025-05-11 15:04:06.354988

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6f36f76e4a'
down_revision: Union[str, None] = 'f5f5c9e1b6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('need_update', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'need_update')
    # ### end Alembic commands ###
