"""1.4

Revision ID: 7399881aca9b
Revises: 122afb659322
Create Date: 2025-05-31 08:19:53.659737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7399881aca9b'
down_revision: Union[str, None] = '122afb659322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('last_metadata_update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'last_metadata_update_time')
    # ### end Alembic commands ###
