"""1.2

Revision ID: 96cbb67285a6
Revises: d389e61aa053
Create Date: 2025-05-31 02:23:29.900048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96cbb67285a6'
down_revision: Union[str, None] = 'd389e61aa053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.Column('subtitle', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.Column('tv_category', mysql.ENUM('HOT_CN_DRAMA', 'HOT_US_EU_DRAMA', 'HOT_JP_DRAMA', 'HOT_KR_DRAMA', 'HOT_ANIME', 'OTHER'), nullable=True),
    sa.Column('total_episodes', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(collation='utf8mb3_bin', length=255), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('last_update_time', mysql.DATETIME(), nullable=True),
    sa.Column('quark_disk_info', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=False)
    # ### end Alembic commands ###
